BOT SAVES QUEEN

In [5]:
def displayPathtoPrincess(n,grid):
    for id, row in enumerate(grid):
        if 'p' in row:
            princess = (id, row.index('p'))
        if 'm' in row:
            me = (id, row.index('m'))
    
    print(grid)
    print(princess)
    print(me)

    dcols = princess[1] - me[1]
    drows = princess[0] - me[0]
    x = abs(drows)
    y = abs(dcols)

    print(drows)
    print(dcols)
    
    return print(''.join([
        'UP\n' * abs(drows) if drows < 0 else 'DOWN\n' * drows,
        'LEFT\n' * abs(dcols) if dcols < 0 else 'RIGHT\n' * dcols]))
    
#print all the moves here

m = int(input())
grid = [] 
for i in range(0, m): 
    grid.append(input().strip())

displayPathtoPrincess(m,grid)

['---', 'm--', '--p']
(2, 2)
(1, 0)
1
2
DOWN
RIGHT
RIGHT



(None, 0.6)

BOT SAVES QUEEN 2

In [15]:
def nextMove(n,c,r,grid):
    
    for idx, row in enumerate(grid):
        if 'p' in row:
            princess = (idx, row.index('p'))

    if princess[0] - r < 0:
        move = "UP"
    if princess[0] - r > 0:
        move = "DOWN"
    if princess[1] - c < 0:
        move = "LEFT"
    if princess[1] - c > 0:
        move = "RIGHT"

    return move

n = int(input())
r,c = [int(i) for i in input().strip().split()]
grid = []
for i in range(0, n):
    grid.append(input())

print(nextMove(n,c,r,grid))

BOT CLEAN

In [2]:
def next_move(posr, posc, board):
    dirty_cells = [(i, j) for i in enumerate(board) for j in range(5) if board[i][j] == 'd']

    if not dirty_cells:
        return

    closest_dirty_cell = min(dirty_cells, key=lambda x: abs(posr - x[0]) + abs(posc - x[1]))

    if posr < closest_dirty_cell[0]:
        print("DOWN")
    elif posr > closest_dirty_cell[0]:
        print("UP")
    elif posc < closest_dirty_cell[1]:
        print("RIGHT")
    elif posc > closest_dirty_cell[1]:
        print("LEFT")
    else:
        print("CLEAN")

if __name__ == "__main__":
    pos = [int(i) for i in input().strip().split()]
    board = [[j for j in input().strip()] for i in range(5)]
    next_move(pos[0], pos[1], board)


DOWN


In [ ]:
def next_move(posr, posc, board):
    dirty_cells = ((i, j) for i, row in enumerate(board) if 'd' in row for j, c in enumerate(row) if c == 'd')
    i, j = min(dirty_cells, key=lambda x: abs(posr - x[0]) + abs(posc - x[1]))
    print("LEFT" if j < posc else "RIGHT" if j > posc else "UP" if i < posr else "DOWN" if i > posr else "CLEAN")

if __name__ == "__main__":
    pos = [int(i) for i in input().strip().split()]
    board = [[j for j in input().strip()] for i in range(5)]
    next_move(pos[0], pos[1], board)


BOT CLEAN STOCHASTIC

BOT CLEAN LARGE

In [ ]:
def next_move(posx, posy, dimx, dimy, board):
    dirty_cells = [(i, j) for i in range(dimx) for j in range(dimy) if board[i][j] == 'd']

    if not dirty_cells:
        print("No more dirty cells.")
        return

    next_dirty = min(dirty_cells, key=lambda x: abs(posx - x[0]) + abs(posy - x[1]))

    if posx < next_dirty[0]:
        print("DOWN")
    elif posx > next_dirty[0]:
        print("UP")
    elif posy < next_dirty[1]:
        print("RIGHT")
    elif posy > next_dirty[1]:
        print("LEFT")
    else:
        print("CLEAN")

# Sample Input
initial_location = list(map(int, input().split()))
height, width = map(int, input().split())
matrix = [input() for _ in range(height)]

# Calling the function with sample input
next_move(initial_location[0], initial_location[1], height, width, matrix)

In [ ]:
def next_move(posx, posy, dimx, dimy, board):
    dirty_cells = [(i, j) for i in range(dimx) for j in range(dimy) if board[i][j] == 'd']

    if not dirty_cells:
        print("No more dirty cells.")
        return

    i,j = min(dirty_cells, key=lambda x: abs(posx - x[0]) + abs(posy - x[1]))
    
    print("LEFT" if j < posy else "RIGHT" if j > posy else "UP" if i < posx else "DOWN" if i > posx else "CLEAN")


if __name__ == "__main__":
    pos = [int(i) for i in input().strip().split()]
    dim = [int(i) for i in input().strip().split()]
    board = [[j for j in input().strip()] for i in range(dim[0])]
    next_move(pos[0], pos[1], dim[0], dim[1], board)

BOT CLEAN PARTIALLY OBSV

In [ ]:
def next_move(posx, posy, board):
    visible_cells = [
        (i, j) for i in range(posx-1, posx+2) for j in range(posy-1, posy+2)
        if 0 <= i < 5 and 0 <= j < 5 and board[i][j] != 'o'
    ]

    dirty_cells = [(i, j) for i, j in visible_cells if board[i][j] == 'd']

    if not dirty_cells:
        print("RIGHT" if posy < len(board)-len(board)//2 else "DOWN" if posx < len(board)-len(board)//2 and 
              posy == len(board)-1 else "LEFT" if posy > (len(board)-len(board)//2) else "UP" if posx > 
              len(board)-len(board)//2 and posy == 0 else "")
    else :
        i, j = min(dirty_cells, key=lambda x: abs(posx - x[0]) + abs(posy - x[1]))
        print("LEFT" if j < posy else "RIGHT" if j > posy else "UP" if i < posx else "DOWN" if i > posx else "CLEAN")

if __name__ == "__main__": 
    pos = [int(i) for i in input().strip().split()] 
    board = [[j for j in input().strip()] for i in range(5)]  
    next_move(pos[0], pos[1], board)


MAZE ESCAPE

In [ ]:
def next_move(player, board):
    #print("Player: {}".format(player))
    move = ''
    # Start
    for i in range(len(board)):
        for j in range(len(board[i])):
            if i == 1  and j == 0 and board[i][j] == 'e':
                move = 'LEFT'
            else :  
                if i == 0 and j == 1 and board[i][j] == '-':
                    move = 'UP'
                if i == 0 and j == 1 and board[i][j] == '#':
                    move = 'RIGHT'
    
    print(move)

# Start application
if __name__ == "__main__":
    # Set data
    player = int(input())
    board = [[j for j in input().strip()] for i in range(3)]  
    next_move(player, board)

In [ ]:
def next_move(player, board):
    #print("Player: {}".format(player))
    move = ''
    # Start
    if board[1][0] == 'e':
        move = 'LEFT'
    else :  
        if board[0][1] == '-':
            move = 'UP'
        if board[0][1] == '#' and board[1][2] == "#":
            move = 'LEFT'
        elif board[0][1] == "#" :
            move = 'RIGHT'
 
            
    
    print(move)

# Start application
if __name__ == "__main__":
    # Set data
    player = int(input())
    board = [[j for j in input().strip()] for i in range(3)]  
    next_move(player, board)

Click-o-Mania

In [ ]:
def nextMove(x, y, k, grid):
    def dfs(row, col, color, visited, component):
        if (
            0 <= row < x
            and 0 <= col < y
            and grid[row][col] == color
            and not visited[row][col]
        ):
            visited[row][col] = True
            component.append((row, col))

            # Check in all four directions
            dfs(row + 1, col, color, visited, component)
            dfs(row - 1, col, color, visited, component)
            dfs(row, col + 1, color, visited, component)
            dfs(row, col - 1, color, visited, component)

    coordinates = []

    for i in range(x):
        for j in range(y):
            if grid[i][j] != '-':
                coordinates.append((i, j))

    if not coordinates:
        return None

    visited = [[False] * y for _ in range(x)]
    all_components = []

    for coord in coordinates:
        if not visited[coord[0]][coord[1]]:
            component = []
            dfs(coord[0], coord[1], grid[coord[0]][coord[1]], visited, component)
            all_components.append(component)

    # Sort components by size (ascending)
    all_components.sort(key=len)

    # Select the first block of the smallest component with at least 2 boxes
    for component in all_components:
        if len(component) >= 2:
            return component[0]

    return None

# Sample Input
x, y, k = map(int, input().split())
grid = [input().strip() for _ in range(x)]

# Get the next move
result = nextMove(x, y, k, grid)

# Output the result
if result:
    print(result[0], result[1])
else:
    print("No move available")


Battery Life

In [31]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Read training data from file
with open("batterylife.txt", "r") as file:
    lines = file.readlines()

# Parse training data and filter out data points where battery life is 8
data = [list(map(float, line.strip().split(','))) for line in lines if float(line.strip().split(',')[1]) != 8]
charging_times = np.array([item[0] for item in data]).reshape(-1, 1)
battery_life = np.array([item[1] for item in data])

# Train the linear regression model
model = LinearRegression()
model.fit(charging_times, battery_life)

# Function to predict battery life based on charging time
def predict_battery_life(charging_time):
    return model.predict(np.array([[charging_time]]))[0]

if __name__ == '__main__':
    timeCharged = float(input().strip())

    # Predict battery life using the trained model
    predicted_life = predict_battery_life(timeCharged)

    # Output the result rounded to 2 decimal places
    # max battery life == 8.
    if predicted_life > 8.0:
        print(8.0)
    else :
        print(f"{predicted_life:.2f}")


8.0


LIGHTS OUT

In [ ]:
def is_valid_move(grid, r, c):
    return 0 <= r < 8 and 0 <= c < 8 and grid[r][c] == 1

def flip_cells(grid, r, c):
    grid[r][c] = 1 - grid[r][c]  # flip the current cell
    if is_valid_move(grid, r, c + 1):
        grid[r][c + 1] = 1 - grid[r][c + 1]  # flip the cell to the right
    if is_valid_move(grid, r + 1, c):
        grid[r + 1][c] = 1 - grid[r + 1][c]  # flip the cell below

def print_grid(grid):
    for row in grid:
        print("".join(map(str, row)))

def play_game():
    player = int(input())
    grid = [list(map(int, input().strip())) for _ in range(8)]

    for _ in range(100):  # maximum 100 moves
        for i in range(8):
            for j in range(8):
                if grid[i][j] == player:
                    flip_cells(grid, i, j)
                    print(i, j)
                    print_grid(grid)
                    return

if __name__ == "__main__":
    play_game()


Stock Prediction

In [ ]:
import numpy as np
import requests

def fetch_data(url):
    response = requests.get(url)
    lines = response.text.strip().split('\n')
    return lines

def printTransactions(m, k, d, name, owned, prices):
    for i in range(k):
        stock_name = name[i]
        stock_owned = owned[i]
        stock_prices = prices[i]

        current_price = stock_prices[-1]
        avg_price = np.mean(stock_prices[:-1])

        if d > 0:
            if stock_owned > 0 and current_price > avg_price:
                # If you own stocks and the current price is higher than the average, sell some
                sell_amount = min(stock_owned, int(m / current_price))
                print(f"1\n{stock_name} SELL {sell_amount}")
                m += sell_amount * current_price  # Add money from selling to the available money
            elif stock_owned == 0 and current_price < avg_price:
                # If you don't own stocks and the current price is lower than the average, buy some
                buy_amount = min(int(m / current_price), int(m / avg_price))
                print(f"1\n{stock_name} BUY {buy_amount}")
                m -= buy_amount * current_price  # Subtract money spent on buying
        else:
            # On the last day, sell any remaining stocks
            if stock_owned > 0:
                print(f"1\n{stock_name} SELL {stock_owned}")

if __name__ == "__main__":
    # Load data from the provided link
    url = "http://s3.amazonaws.com/hr-testcases-us-east-1/329/assets/bigger_data_set.txt"
    data_lines = fetch_data(url)

    # Parse input data
    m, k, d = map(float, data_lines[0].strip().split()[:3])  # Change int to float
    name, owned, prices = [], [], []
    for i in range(1, len(data_lines), k + 1):
        stock_data = data_lines[i:i+k]
        stock_name, stock_owned, *stock_prices = stock_data
        try:
            owned.append(int(stock_owned.split()[1]))  # Extract the numeric part from 'owned'
        except ValueError:
            owned.append(0)  # Handle non-integer values gracefully
        prices.append([float(price) if price.replace('.', '', 1).isdigit() else 0.0 for price in stock_prices])

    # Execute the trading strategy
    printTransactions(m, k, d, name, owned, prices)


BASIC STATISTIC WARMUP

In [12]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from statistics import mean, median
from math import sqrt

def custom_mode(numbers):
    # Custom mode function to handle multiple modes
    frequencies = {}
    for num in numbers:
        frequencies[num] = frequencies.get(num, 0) + 1

    max_frequency = max(frequencies.values())
    mode_values = [key for key, value in frequencies.items() if value == max_frequency]

    return mode_values

def calculate_confidence_interval(mean, std_dev, n):
    z_score = 1.96  # Assuming normal distribution
    margin_of_error = z_score * (std_dev / sqrt(n))
    lower_boundary = mean - margin_of_error
    upper_boundary = mean + margin_of_error
    return lower_boundary, upper_boundary

def main():
    # Input
    N = int(input())
    numbers = list(map(int, input().split()))

    # Mean
    mean_value = mean(numbers)
    print(f"{mean_value:.1f}")

    # Median
    median_value = median(numbers)
    print(f"{median_value:.1f}")

    # Mode
    mode_values = custom_mode(numbers)
    mode_values = sorted(mode_values)
    print(mode_values[0])

    # Standard Deviation
    std_dev = sqrt(sum((x - mean_value) ** 2 for x in numbers) / N)
    print(f"{std_dev:.1f}")

    # Confidence Interval
    lower_boundary, upper_boundary = calculate_confidence_interval(mean_value, std_dev, N)
    print(f"{lower_boundary:.1f} {upper_boundary:.1f}")

if __name__ == "__main__":
    main()



43900.6
44627.5
4978
30466.9
25017.0 62784.2


Image Segmentation 4-connectivity

In [ ]:
def count_objects(image):
    rows, cols = len(image), len(image[0])
    visited = [[False] * cols for _ in range(rows)]

    def is_valid(x, y):
        return 0 <= x < rows and 0 <= y < cols

    def dfs(x, y):
        if not is_valid(x, y) or visited[x][y] or image[x][y] == '0':
            return
        visited[x][y] = True
        directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            dfs(nx, ny)
            print(x,y)

    object_count = 0
    for i in range(rows):
        for j in range(cols):
            if not visited[i][j] and image[i][j] == '1':
                print(f"OBJEK {object_count+1}")
                dfs(i, j)
                object_count += 1

    return object_count

# Input binary image
binary_image = [
    '000110001010',
    '111011110001',
    '111010010010',
    '100000000100'
]

# Count 4-connected objects
result = count_objects(binary_image)
print(result)


8-connectivity

In [17]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

def count_objects(image):
    rows, cols = len(image), len(image[0])
    visited = [[False] * cols for _ in range(rows)]
    
    def is_valid(x, y):
        return 0 <= x < rows and 0 <= y < cols

    def dfs(x, y):
        if not is_valid(x, y) or visited[x][y] or image[x][y] == '0':
            return
        visited[x][y] = True
        
        #8-connectivity
        directions = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1)]
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            dfs(nx, ny)

    object_count = 0
    for i in range(rows):
        for j in range(cols):
            if not visited[i][j] and image[i][j] == '1':
                dfs(i, j)
                object_count += 1
            
    return object_count

    
def main():
    result = count_objects((input().split()))
    print(result)

if __name__ == "__main__":
    main()



2


Dilation

In [30]:
import numpy as np

input_string = """0000000000
0111111100
0000111100
0000111100
0001111100
0000111100
0001100000
0000000000"""

input_structuring_element = """111
111
111"""

# Split the input string by newline characters and convert each line into a list of integers
image = [[int(char) for char in line] for line in input_string.split('\n')]
se = [[int(char) for char in line] for line in input_structuring_element.split('\n')]


def dilate(image, structuring_element):
    rows = len(image)
    cols = len(image[0])
    struct_rows = len(structuring_element)
    struct_cols = len(structuring_element[0])
    result = [[0] * cols for _ in range(rows)]

    for i in range(rows):
        for j in range(cols):
            if image[i][j] == 1:
                #tidak terpakai sebenernya di fungsi dilation (tidak penting)
                for m in range(struct_rows):
                    for n in range(struct_cols):
                        if structuring_element[m][n] == 1:
                            #langsung sini bisya
                            for p in range(-1, 2):
                                for q in range(-1, 2):
                                    if i+p >= 0 and i+p < rows and j+q >= 0 and j+q < cols:
                                        result[i+p][j+q] = 1

    return result
    
dilated_image = dilate(image, se)

marked_pixels = sum(sum(row) for row in dilated_image)

np_dilated_image = np.array(dilated_image)

print(np_dilated_image)


[[1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 0 0 0 0]]


In [17]:
import numpy as np

# Original image
image = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,1,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,1,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])

# Structuring element
structuring_element = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])

# Function to perform dilation operation
def dilation(image, structuring_element):
    result = np.zeros_like(image)
    m, n = structuring_element.shape
    for i in range(image.shape[0] - m + 1):
        for j in range(image.shape[1] - n + 1):
            if np.all(image[i:i+m, j:j+n] == structuring_element):
                result[i+(m//2), j+(n//2)] = 1
    return result

# Function to perform erosion operation
def erosion(image, structuring_element):
    result = np.zeros_like(image)
    m, n = structuring_element.shape
    for i in range(image.shape[0] - m + 1):
        for j in range(image.shape[1] - n + 1):
            if np.all(image[i:i+m, j:j+n] == structuring_element):
                result[i+(m//2), j+(n//2)] = 1
    return result

# Perform closing operation (dilation followed by erosion)
dilated_image = dilation(image, structuring_element)
result_image = erosion(dilated_image, structuring_element)

# Count number of pixels marked as 1
num_pixels_1 = np.sum(result_image)

print("Number of pixels marked as 1 after closing:", num_pixels_1)
print(dilated_image)


Number of pixels marked as 1 after closing: 0
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


Erosion

In [9]:
import numpy as np

# Original image
image = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,1,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,1,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])

# Structuring element
structuring_element = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])

print(image)
print("Image Awal")

# Function to perform erosion operation
def erosion(image, structuring_element):
    step = 0
    result = np.zeros_like(image)
    m, n = structuring_element.shape
    for i in range(image.shape[0] - m + 1):
        for j in range(image.shape[1] - n + 1):
            if np.all(image[i:i+m, j:j+n] == structuring_element):
                step += 1
                result[i+(m//2), j+(n//2)] = 1
                print(result)
                print("Step ke-"+str(step))
    return result

# Perform erosion operation
result_image = erosion(image, structuring_element)

# Count number of pixels marked as 1
num_pixels_1 = np.sum(result_image)

print("Number of pixels marked as 1 after erosion:", num_pixels_1)


[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 1 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Image Awal
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Step ke-1
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Step ke-2
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Step ke-3
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 

CLOSING

In [39]:
import numpy as np

# Original image
image = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,1,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,1,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])

# Structuring element
structuring_element = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])


def dilate(image, structuring_element):
    rows = len(image)
    cols = len(image[0])
    struct_rows = len(structuring_element)
    struct_cols = len(structuring_element[0])
    result = [[0] * cols for _ in range(rows)]

    for i in range(rows):
        for j in range(cols):
            if image[i][j] == 1:
                #tidak terpakai sebenernya di fungsi dilation (tidak penting)
                for m in range(struct_rows):
                    for n in range(struct_cols):
                        if structuring_element[m][n] == 1:
                            #langsung sini bisya
                            for p in range(-1, 2):
                                for q in range(-1, 2):
                                    if i+p >= 0 and i+p < rows and j+q >= 0 and j+q < cols:
                                        result[i+p][j+q] = 1

    return result

def erosion(image, structuring_element):
    result = np.zeros_like(image)
    m, n = structuring_element.shape
    for i in range(image.shape[0] - m + 1):
        for j in range(image.shape[1] - n + 1):
            if np.all(image[i:i+m, j:j+n] == structuring_element):
                result[i+(m//2), j+(n//2)] = 1
    return result

#closing is combination of dilation into erosion
dilated_image = dilate(image, structuring_element)
np_dilated_image = np.array(dilated_image)
eroded_image = erosion(np_dilated_image, structuring_element)

num_pixels = sum(sum(row) for row in eroded_image)

print(num_pixels)




29


In [21]:
#using scipy
import numpy as np

# Original image
image = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,1,1,1,1,1,0,0],
    [0,0,0,0,1,1,1,1,0,0],
    [0,0,0,1,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])

# Structuring element
structuring_element = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])

# Function to perform dilation operation
def dilation(image, structuring_element):
    from scipy.ndimage import binary_dilation
    return binary_dilation(image, structure=structuring_element)

# Function to perform erosion operation
def erosion(image, structuring_element):
    from scipy.ndimage import binary_erosion
    return binary_erosion(image, structure=structuring_element)

# Perform closing operation (dilation followed by erosion)
dilated_image = dilation(image, structuring_element)
result_image = erosion(dilated_image, structuring_element)

# Count number of pixels marked as 1
num_pixels_1 = np.sum(result_image)

print("Number of pixels marked as 1 after closing:", num_pixels_1)
print(dilated_image)


Number of pixels marked as 1 after closing: 29
[[ True  True  True  True  True  True  True  True  True False]
 [ True  True  True  True  True  True  True  True  True False]
 [ True  True  True  True  True  True  True  True  True False]
 [False False  True  True  True  True  True  True  True False]
 [False False  True  True  True  True  True  True  True False]
 [False False  True  True  True  True  True  True  True False]
 [False False  True  True  True  True  True  True  True False]
 [False False  True  True  True  True False False False False]
 [False False False False False False False False False False]]


In [40]:
#wihout numpy
input_string = """0000000000
0111111100
0000111100
0000111100
0001111100
0000111100
0001100000
0000000000"""

input_structuring_element = """111
111
111"""

# Split the input string by newline characters and convert each line into a list of integers
image = [[int(char) for char in line] for line in input_string.split('\n')]
se = [[int(char) for char in line] for line in input_structuring_element.split('\n')]

def dilate(image, structuring_element):
    rows = len(image)
    cols = len(image[0])
    struct_rows = len(structuring_element)
    struct_cols = len(structuring_element[0])
    result = [[0] * cols for _ in range(rows)]

    for i in range(rows):
        for j in range(cols):
            if image[i][j] == 1:
                #tidak terpakai sebenernya di fungsi dilation (tidak penting)
                for m in range(struct_rows):
                    for n in range(struct_cols):
                        if structuring_element[m][n] == 1:
                            #langsung sini bisya
                            for p in range(-1, 2):
                                for q in range(-1, 2):
                                    if i+p >= 0 and i+p < rows and j+q >= 0 and j+q < cols:
                                        result[i+p][j+q] = 1

    return result

def erosion(image, structuring_element):
    result = [[0]*len(image[0]) for _ in range(len(image))]
    m, n = len(structuring_element), len(structuring_element[0])
    for i in range(len(image) - m + 1):
        for j in range(len(image[0]) - n + 1):
            if all(image[i+x][j+y] == 1 for x in range(m) for y in range(n)):
                for x in range(m):
                    for y in range(n):
                        result[i+(m//2)][j+(n//2)] = 1
    return result


#closing is combination of dilation into erosion
dilated_image = dilate(image, se)
eroded_image = erosion(dilated_image, se)

num_pixels = sum(sum(row) for row in eroded_image)

print(num_pixels)


29


OPENING

In [4]:
#wihout numpy
input_string = """0000000000
0111111100
0000111100
0000111100
0001111100
0000111100
0001100000
0000000000"""

input_structuring_element = """111
111
111"""

# Split the input string by newline characters and convert each line into a list of integers
image = [[int(char) for char in line] for line in input_string.split('\n')]
se = [[int(char) for char in line] for line in input_structuring_element.split('\n')]

def dilate(image, structuring_element):
    rows = len(image)
    cols = len(image[0])
    struct_rows = len(structuring_element)
    struct_cols = len(structuring_element[0])
    result = [[0] * cols for _ in range(rows)]

    for i in range(rows):
        for j in range(cols):
            if image[i][j] == 1:
                #tidak terpakai sebenernya di fungsi dilation (tidak penting)
                for m in range(struct_rows):
                    for n in range(struct_cols):
                        if structuring_element[m][n] == 1:
                            #langsung sini bisya
                            for p in range(-1, 2):
                                for q in range(-1, 2):
                                    if i+p >= 0 and i+p < rows and j+q >= 0 and j+q < cols:
                                        result[i+p][j+q] = 1

    return result

def erosion(image, structuring_element):
    result = [[0]*len(image[0]) for _ in range(len(image))]
    m, n = len(structuring_element), len(structuring_element[0])
    for i in range(len(image) - m + 1):
        for j in range(len(image[0]) - n + 1):
            if all(image[i+x][j+y] == 1 for x in range(m) for y in range(n)):
                for x in range(m):
                    for y in range(n):
                        result[i+(m//2)][j+(n//2)] = 1
    return result


#opening is combination of erosion into dilation
eroded_image = erosion(image, se)
dilated_image = dilate(eroded_image, se)


num_pixels = sum(sum(row) for row in dilated_image)

print(num_pixels)


20


EROSION WITH UNUSUAL KERNEL

In [21]:
def erosion(image, structuring_element):
    result = []
    for i in range(len(image)):
        row = ''
        for j in range(len(image[0])):
            # Check if all neighbors as defined by the structuring element are 1s
            if all(0 <= i + k < len(image) and 0 <= j < len(image[0]) and image[i+k][j] == 1 for k in range(-1, 2)):
                row += '1'
            else:
                row += '0'
        result.append(row)
    return result

# Original image
image = [
    [0,0,1,1,0],
    [0,0,1,1,0],
    [0,0,1,1,0],
    [1,1,1,1,1]
]

# Structuring element
structuring_element = [
    [1],
    [1],
    [1]
]

# Perform erosion
result = erosion(image, structuring_element)

# Print the resulting image
for row in result:
    print(row)


00000
00110
00110
00000


In [14]:
#wihout numpy
input_string = """00110
00110
00110
11111"""

input_structuring_element = """1
1
1"""

# Split the input string by newline characters and convert each line into a list of integers
image = [[int(char) for char in line] for line in input_string.split('\n')]
se = [[int(char) for char in line] for line in input_structuring_element.split('\n')]

def erosion(image, structuring_element):
    result = [[0]*len(image[0]) for _ in range(len(image))]
    m, n = len(structuring_element), len(structuring_element[0])
    for i in range(len(image) - m + 1):
        for j in range(len(image[0]) - n + 1):
            if all(image[i+x][j+y] == 1 for x in range(m) for y in range(n)):
                for x in range(m):
                    for y in range(n):
                        result[i+(m//2)][j+(n//2)] = 1
    return result


eroded_image = erosion(image, se)

num_pixels = sum(sum(row) for row in eroded_image)
 
result = '\n'.join([''.join(map(str,row)) for row in eroded_image])

print(result)

00000
00110
00110
00000


DILATION WITH UNUSUAL KERNEL

In [1]:
#wihout numpy
input_string = """0000
0110
0000"""

input_structuring_element = """10
11"""

# Split the input string by newline characters and convert each line into a list of integers
image = [[int(char) for char in line] for line in input_string.split('\n')]
se = [[int(char) for char in line] for line in input_structuring_element.split('\n')]

def dilate(image, structuring_element):
    rows = len(image)
    cols = len(image[0])
    result = [[0] * cols for _ in range(rows)]

    for i in range(rows):
        for j in range(cols):
            if image[i][j] == 1:
                for p in range(-1, 1):
                    for q in range(0, 2):
                        if i+p >= 0 and i+p < rows and j+q >= 0 and j+q < cols:
                            if structuring_element[p+1][q] == 1:
                                result[i+p][j+q] = 1

    return result


dilated_image = dilate(image, se)

num_pixels = sum(sum(row) for row in dilated_image)
 
result = '\n'.join([''.join(map(str,row)) for row in dilated_image])

print(result)

0110
0111
0000


Day and Night

In [7]:
import numpy as np

def detect_day_or_night(image):
    # Calculate the average brightness of the image
    image_np = np.zeros((len(image), len(image[0]), 3), dtype=int)
    for i in range(len(image)):
        for j in range(len(image[0])):
            pixel_values = image[i][j].split(',')
            image_np[i, j] = [int(value) for value in pixel_values]
    
    average_brightness = np.mean(image_np) * 100 / 255
    
    # Define a threshold value to classify images
    threshold = 50  # Adjust this threshold as needed
    
    # Classify the image as day or night based on the average brightness
    if average_brightness > threshold:
        return 'day'
    else:
        return 'night'

# Read the input image from STDIN
image = []
while True:
    try:
        row = input().strip().split()
        image.append(row)
    except EOFError:
        break

# Detect day or night
result = detect_day_or_night(image)
print(result)


33.08641975308642
night


In [23]:
image_np = np.zeros((3, 3, 3), dtype=int)

In [24]:
image_np

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [29]:
image_np[0,0] = [10,10,10]

In [35]:
image_np[0,0]

array([10, 10, 10])